name: budget_app
description: A Flutter budgeting app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^8.0.0
  intl: ^0.18.1
  open_file: ^3.3.1  
  uuid: ^3.0.7 

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true